# Generated by Django 5.2 on 2025-06-16 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plataformas',
            new_name='Plataformaxs',
        ),
    ]
