# Generated by Django 5.2 on 2025-06-16 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_plataformas_plataformaxs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plataformaxs',
            new_name='Consola',
        ),
    ]
