# Generated by Django 5.2 on 2025-06-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_plataformaxs_consola'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consola',
            table='consola',
        ),
    ]
