# Generated by Django 5.2 on 2025-06-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_consola_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consola',
            table=None,
        ),
    ]
